# -*- coding: utf-8 -*-
"""Contact Tracing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVjWTlGKkqjHfIhZ6_TeG0EfMJHzeWqU
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import datetime as dt
from sklearn.cluster import DBSCAN
df = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Machine Learning/Tracking the covid spread/MOCK_DATA.json')
df.head(10)

"""Visualize the people on graph using those id's"""

plt.figure(figsize=(8,6))
sns.scatterplot(x='Latitude', y='Longitude', data=df, hue='User' , style='User',size='User')
plt.legend(bbox_to_anchor= [1, 0.8])
plt.show()

epsilon = 0.0018288 # a radial distance of 6 feet in kilometers
model = DBSCAN(eps=epsilon, min_samples=2, metric='haversine').fit(df[['Latitude', 'Longitude']])
df['cluster'] = model.labels_.tolist()

def get_infected_names(input_name):   
    
    input_name_clusters = []
    for i in range(len(df)):
        if df['User'][i] == input_name:
            if df['cluster'][i] in input_name_clusters:
                pass
            else:
                input_name_clusters.append(df['cluster'][i])
    
    infected_names = []
    for cluster in input_name_clusters:
        if cluster != -1:
            ids_in_cluster = df.loc[df['cluster'] == cluster, 'User']
            for i in range(len(ids_in_cluster)):
                member_id = ids_in_cluster.iloc[i]
                if (member_id not in infected_names) and (member_id != input_name):
                    infected_names.append(member_id)
                else:
                    pass
    return infected_names

labels = model.labels_
fig = plt.figure(figsize=(12,10))
sns.scatterplot(df['Latitude'], df['Longitude'], hue = ['cluster-{}'.format(x) for x in labels])
plt.legend(bbox_to_anchor = [1, 1])
plt.show()

print(get_infected_names('William'))